[package]
name = "statusline"
version = "0.17.0"
edition = "2021"
description = "Simple and fast bash PS1 line with useful features"
license-file = "license.txt"
repository = "https://git.yukii.keenetic.pro/yuki0iq/statusline"

[dependencies]
pwd = "1.4"
chrono = "0.4"
terminal_size = "0.3"
anyhow = "1.0"
mmarinus = "0.4"
fahtsex = "0.2"
unicode-width = "0.1"
base64 = "0.21"
orion = "0.17"
rustix = { version = "0.38.34", features = ["fs", "process", "stdio"] }
libc = "0.2.155"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

