[package]
name = "statusline"
version = "0.13.1"
edition = "2021"
description = "Simple and fast bash PS1 line with useful features"
license-file = "license.txt"
repository = "https://git.yukii.keenetic.pro/yuki0iq/statusline"

[dependencies]
pwd = "1.4.0"
nix = { version = "0.26.2", features = ["fs", "user"] }
chrono = "0.4.26"
term_size = "0.3.2"
anyhow = "1.0.72"
mmarinus = "0.4.0"
fahtsex = "0.2.0"
unicode-width = "0.1.11"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

