[package]
name = "statusline"
version = "0.10.0"
edition = "2021"
description = "Simple and fast bash PS1 line with useful features"
license-file = "license.txt"
repository = "https://git.yukii.keenetic.pro/yuki0iq/statusline"

[dependencies]
sha256 = "1.2.1"
pwd = "1.4.0"
nix = { version = "0.26.2", features = ["fs", "user"] }
chrono = "0.4.26"
term_size = "0.3.2"
libc = "0.2.147"
anyhow = "1.0.72"
mmarinus = "0.4.0"
fahtsex = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

