[package]
name = "bash-status-line-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.1"
const_format = "0.2.31"
sha256 = "1.2.1"
pwd = "1.4.0"

